### ISSUE TITLE
Demo on codesandbox.io isn't working anymore

### ISSUE THREAD

**Issue by danieledelgiudice** [kristian240/chakra-ui-bottom-navigation#4]
Not sure if this is still being maintained, but it looks like the [demo]( https://codesandbox.io/s/chakra-ui-bottom-navigation-example-kp7hk?file=/src/index.tsx ) isn't working anymore

It might be an issue with some dependencies, this is the stack trace:

```
TypeError: (0 , _react.useSyncExternalStore) is not a function
    at ToastProvider (https://kp7hk.csb.app/node_modules/@chakra-ui/toast/dist/index.esm.js:540:47)
    at renderWithHooks (https://kp7hk.csb.app/node_modules/react-dom/cjs/react-dom.development.js:14985:18)
    at mountIndeterminateComponent (https://kp7hk.csb.app/node_modules/react-dom/cjs/react-dom.development.js:17811:13)
    at beginWork (https://kp7hk.csb.app/node_modules/react-dom/cjs/react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback (https://kp7hk.csb.app/node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (https://kp7hk.csb.app/node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (https://kp7hk.csb.app/node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at beginWork$1 (https://kp7hk.csb.app/node_modules/react-dom/cjs/react-dom.development.js:23964:7)
    at performUnitOfWork (https://kp7hk.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22776:12)
    at workLoopSync (https://kp7hk.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22707:5)
    at renderRootSync (https://kp7hk.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22670:7)
    at performSyncWorkOnRoot (https://kp7hk.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22293:18)
    at scheduleUpdateOnFiber (https://kp7hk.csb.app/node_modules/react-dom/cjs/react-dom.development.js:21881:7)
    at updateContainer (https://kp7hk.csb.app/node_modules/react-dom/cjs/react-dom.development.js:25482:3)
    at eval (https://kp7hk.csb.app/node_modules/react-dom/cjs/react-dom.development.js:26021:7)
    at unbatchedUpdates (https://kp7hk.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22431:12)
    at legacyRenderSubtreeIntoContainer (https://kp7hk.csb.app/node_modules/react-dom/cjs/react-dom.development.js:26020:5)
    at render (https://kp7hk.csb.app/node_modules/react-dom/cjs/react-dom.development.js:26103:10)
    at $csb$eval (https://kp7hk.csb.app/src/index.tsx:83:22)
    at H (https://codesandbox.io/static/js/sandbox.d80c679cf.js:1:100039)
    at K.evaluate (https://codesandbox.io/static/js/sandbox.d80c679cf.js:1:112791)
    at ge.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.d80c679cf.js:1:123173)
    at ge.evaluateModule (https://codesandbox.io/static/js/sandbox.d80c679cf.js:1:122672)
    at https://codesandbox.io/static/js/sandbox.d80c679cf.js:1:319322
    at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:4333)
    at Generator._invoke (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:4086)
    at forEach.t.<computed> [as next] (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:4690)
    at e (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:206)
    at a (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:417)
```

**Comment by kristian240** [comment]
Hi there @danieledelgiudice I can see what is the issue, I will take care of this 😄

**Comment by kristian240** [comment]
@danieledelgiudice the demo is working again. Also the v2 is deployed that works with chakra v2

**Comment by danieledelgiudice** [comment]
Woah, that was fast, thanks! 🙂
